### ISSUE TITLE
can you explain how to use your library please? 

### ISSUE THREAD

**Issue by ghost** [DaniPopes/dexscreener#1]
i'm new to rust

**Comment by DaniPopes** [comment]
Sure! This is just a client for the [official Dexscreener API](https://docs.dexscreener.com/api/reference), so it's pretty simple:

```rust
let client = Client::new();
let pair_addresses = [
    "0x7213a321F1855CF1779f42c0CD85d3D95291D34C",
    "0x16b9a82891338f9ba80e2d6970fdda79d1eb0dae",
];
let result = client.pairs("bsc", pair_addresses).await.unwrap().pairs.unwrap();
```

You can also view the automatically generated documentation on [docs.rs](https://docs.rs/dexscreener/latest/dexscreener/).
